<?php

function islandora_image_crop_menu() {
  $items['islandora/image_crop/%'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_image_crop_edit_form', 2, 3),
    'access arguments' => array('islandora crop datastream image'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function islandora_image_crop_islandora_edit_datastream_registry($object, $ds_id) {
  if ($ds_id == 'MEDIUM_SIZE') {
    return array(
      array(
        'Name' => t('Islandora Image Crop'),
        'url' => 'islandora/image_crop/' . $object->id . '/' . $ds_id, 
        'weight' => 5,
      ),
    );
  }
}

function islandora_image_crop_edit_form($form, &$form_state, $pid, $ds_id = NULL) {
  $js_path = drupal_get_path('module', 'islandora_image_crop') . '/js/';
  drupal_add_js($js_path . 'jquery.Jcrop.min.js');
  drupal_add_js($js_path . 'islandora_image_crop.js');
  
  $form = array();
  
  global $base_url;
  
  $image_url = $base_url . '/islandora/object/' . $pid . '/datastream/' . $ds_id . '/view';
  
  $form['image'] = array(
    '#markup' => theme('image', array('path' => $image_url));
  );
  
  $form['image_action'] = array(
    '#type' => 'radios',
    '#title' => t('Action'),
    '#description' => t('What should be done with the cropped image?'),
    '#options' => array(0 => t('Replace existing datastream'), 1 => t('Create new datastream')),
  );
  
  $form['new_ds_id'] = array(
    '#type' => 'textfield',
    '#title' => t('New datastream ID'),
    '#description' => t('If creating a new datastream, label the datastream');
  );
  
  $form['x'] = array(
    '#type' => 'hidden',
  );
  
  $form['y'] = array(
    '#type' => 'hidden',
  );
  
  $form['w'] = array(
    '#type' => 'hidden',
  );
  
  $form['h'] = array(
    '#type' => 'hidden',
  );
  
  $form['ds_id'] = array(
    '#type' => 'value',
    '#value' => $ds_id,
  );
  
  $form['pid'] = array(
    '#type' => 'value',
    '#value' => $pid,
  );
  
  return $form;
}

function islandora_image_crop_edit_form_submit($form, &$form_submit) {
  global $base_url;
}